constants:
  exception:
    common-handler:
      enabled: true

spring:
  jpa:
    database: mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 50 # 배치작업 크기 설정
        format_sql: true # 쿼리문 보기편하게 포맷팅
        order_updates: true # JPA Batch 작업 활성화
    show-sql: true # JPA가 쿼리문 로그에 출력