management:
  endpoints:
    web:
      exposure:
        # 모든 엔드포인트를 웹(HTTP)으로 노출 (개발 환경에서만 권장)
        include: "*"
  endpoint:
    health:
      show-details: always # 상세한 상태 정보 표시
    env:
      show-values: always

server:
  tomcat:
    threads:
      max: 200

spring:
  threads:
    virtual:
      enabled: true
  jackson:
    default-property-inclusion: non_null
